repos:
- repo: https://github.com/python/black
  rev: stable
  hooks:
  - id: black
    language: python_venv
    exclude: mysite/settings
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: flake8
    language: python_venv
    exclude: mysite/settings|docs/source/conf.py
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort
    language: python_venv
    exclude: mysite/settings|docs/source/conf.py